name: Update Notion to Discord

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run custom action
      uses: ./path-to-action
      with:
        notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
        notion_token: ${{ secrets.NOTION_TOKEN }}
        discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        discord_token: ${{ secrets.DISCORD_TOKEN }}
```
```

## **3. 配置 GitHub Actions 工作流程**

創建一個 GitHub Actions 工作流程來使用我們的自定義 Action。在 `.github/workflows` 目錄下創建一個新的 YAML 文件，例如 `main.yml`，並添加以下內容：

```yaml
name: Update Notion to Discord

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use custom action
      uses: ./  # 使用自定義 Action 的路徑
      with:
        notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
        notion_token: ${{ secrets.NOTION_TOKEN }}
        discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        discord_token: ${{ secrets.DISCORD_TOKEN }}