name: AutoCorrect Check

on:
    pull_request:

jobs:
    autocorrect:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: AutoCorrect
              uses: huacnlee/autocorrect-action@v2
              with:
                  args: --lint --no-diff-bg-color $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}}
